
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  application:
    name: Lap_Top_Shop
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/laptopshop
    username: root
    password: Anhchodien174@
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: anh0174
      password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080